#security:
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
#        App\Entity\User: sha512
#    role_hierarchy:
#        ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]
#        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
#
#    providers:
#        main:
#            id: fos_user.user_provider.username
#    firewalls:
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#        main:
#            pattern:   ^/
#            anonymous: true
#            provider:  main
#            form_login:
#                login_path: fos_user_security_login
#                check_path: fos_user_security_check
#                default_target_path: fos_user_security_login
#                failure_path: fos_user_security_login
#            logout:
#                path:   fos_user_security_logout
#                target: fos_user_security_login
#                #always_remember_me: true
#    access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY  } # requires_channel: https
#        - { path: ^/request, roles: IS_AUTHENTICATED_ANONYMOUSLY  } # requires_channel: https
#        - { path: ^/platform/create, roles: IS_AUTHENTICATED_ANONYMOUSLY } # , requires_channel: https
#        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                failure_path: fos_user_security_login
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider
            logout:
                path: fos_user_security_logout
                target: /
            anonymous:    true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 604800 # 1 week in seconds
                path:     /
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/person/create, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_FULLY }

