<?php

namespace App\Entity\Repository;

/**
 * RefDepartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefDepartementRepository extends \Doctrine\ORM\EntityRepository
{

}

