<?php

namespace App\Entity\Repository;

/**
 * RefSexeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefTypeEntityRepository extends \Doctrine\ORM\EntityRepository
{

}

